In [1]:
import numpy as np
import pandas as pd

In [2]:
data= pd.read_csv(r"C:\Users\PRAKASH KATIKANENI\Downloads\fish.csv")

In [3]:
data

Species  Weight  Length1  Length2  Length3   Height   Width
0     Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1     Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2     Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3     Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4     Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
..      ...     ...      ...      ...      ...      ...     ...
154   Smelt    12.2     11.5     12.2     13.4   2.0904  1.3936
155   Smelt    13.4     11.7     12.4     13.5   2.4300  1.2690
156   Smelt    12.2     12.1     13.0     13.8   2.2770  1.2558
157   Smelt    19.7     13.2     14.3     15.2   2.8728  2.0672
158   Smelt    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]

In [4]:
data.isnull().any()

Species    False
Weight     False
Length1    False
Length2    False
Length3    False
Height     False
Width      False
dtype: bool

In [5]:
data['Species'].unique()

array(['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt'],
      dtype=object)

In [6]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data['Species']=le.fit_transform(data['Species'])

In [7]:
data


Species  Weight  Length1  Length2  Length3   Height   Width
0          0   242.0     23.2     25.4     30.0  11.5200  4.0200
1          0   290.0     24.0     26.3     31.2  12.4800  4.3056
2          0   340.0     23.9     26.5     31.1  12.3778  4.6961
3          0   363.0     26.3     29.0     33.5  12.7300  4.4555
4          0   430.0     26.5     29.0     34.0  12.4440  5.1340
..       ...     ...      ...      ...      ...      ...     ...
154        5    12.2     11.5     12.2     13.4   2.0904  1.3936
155        5    13.4     11.7     12.4     13.5   2.4300  1.2690
156        5    12.2     12.1     13.0     13.8   2.2770  1.2558
157        5    19.7     13.2     14.3     15.2   2.8728  2.0672
158        5    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]

In [8]:
data['Species'].unique() 

array([0, 4, 6, 1, 2, 3, 5])

In [9]:
x = data.iloc[:,1:7].values
y=data.iloc[:,0:1].values

In [10]:
from sklearn.preprocessing import OneHotEncoder
one =OneHotEncoder()
z=one.fit_transform(y[:,0:1]).toarray()
y=np.delete(y,0,axis=1)
y=np.concatenate((z,y),axis=1)

In [11]:
x

array([[2.42000e+02, 2.32000e+01, 2.54000e+01, 3.00000e+01, 1.15200e+01,
        4.02000e+00],
       [2.90000e+02, 2.40000e+01, 2.63000e+01, 3.12000e+01, 1.24800e+01,
        4.30560e+00],
       [3.40000e+02, 2.39000e+01, 2.65000e+01, 3.11000e+01, 1.23778e+01,
        4.69610e+00],
       [3.63000e+02, 2.63000e+01, 2.90000e+01, 3.35000e+01, 1.27300e+01,
        4.45550e+00],
       [4.30000e+02, 2.65000e+01, 2.90000e+01, 3.40000e+01, 1.24440e+01,
        5.13400e+00],
       [4.50000e+02, 2.68000e+01, 2.97000e+01, 3.47000e+01, 1.36024e+01,
        4.92740e+00],
       [5.00000e+02, 2.68000e+01, 2.97000e+01, 3.45000e+01, 1.41795e+01,
        5.27850e+00],
       [3.90000e+02, 2.76000e+01, 3.00000e+01, 3.50000e+01, 1.26700e+01,
        4.69000e+00],
       [4.50000e+02, 2.76000e+01, 3.00000e+01, 3.51000e+01, 1.40049e+01,
        4.84380e+00],
       [5.00000e+02, 2.85000e+01, 3.07000e+01, 3.62000e+01, 1.42266e+01,
        4.95940e+00],
       [4.75000e+02, 2.84000e+01, 3.10000e+01, 3.6

In [12]:
y

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [14]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [15]:
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.
C:\Users\PRAKASH KATIKANENI\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\PRAKASH KATIKANENI\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\PRAKASH KATIKANENI\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\PRAKASH KATIKANENI\anaconda3\lib

In [16]:
model=Sequential()

In [17]:
x_train.shape

(127, 6)

In [18]:
model.add(Dense(units= 6,init = 'random_uniform' ,activation= 'relu'))

C:\Users\PRAKASH KATIKANENI\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=6, activation="relu", kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [19]:
model.add(Dense(units= 9,init = 'random_uniform' ,activation= 'relu'))

C:\Users\PRAKASH KATIKANENI\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=9, activation="relu", kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [20]:
model.add(Dense(units= 7,init = 'random_uniform' ,activation= 'softmax'))

C:\Users\PRAKASH KATIKANENI\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=7, activation="softmax", kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [21]:
model.compile(optimizer= 'adam' ,loss= 'categorical_crossentropy',metrics= ['accuracy'])

In [22]:
model.fit(x_train,y_train,batch_size=10,epochs=300)


Epoch 1/300
127/127 [==============================] - 0s 977us/step - loss: 1.9432 - accuracy: 0.3071
Epoch 2/300
127/127 [==============================] - 0s 149us/step - loss: 1.9361 - accuracy: 0.3701
Epoch 3/300
127/127 [==============================] - 0s 135us/step - loss: 1.9256 - accuracy: 0.3701
Epoch 4/300
127/127 [==============================] - 0s 165us/step - loss: 1.9099 - accuracy: 0.3701
Epoch 5/300
127/127 [==============================] - 0s 204us/step - loss: 1.8840 - accuracy: 0.3701
Epoch 6/300
127/127 [==============================] - 0s 173us/step - loss: 1.8461 - accuracy: 0.3701
Epoch 7/300
127/127 [==============================] - 0s 165us/step - loss: 1.7959 - accuracy: 0.3701
Epoch 8/300
127/127 [==============================] - 0s 236us/step - loss: 1.7356 - accuracy: 0.3701
Epoch 9/300
127/127 [==============================] - 0s 196us/step - loss: 1.6799 - accuracy: 0.3701
Epoch 10/300
127/127 [==============================] - 0s 157us/step - 

127/127 [==============================] - 0s 141us/step - loss: 1.1323 - accuracy: 0.5591
Epoch 78/300
127/127 [==============================] - 0s 133us/step - loss: 1.1296 - accuracy: 0.5512
Epoch 79/300
127/127 [==============================] - 0s 149us/step - loss: 1.1266 - accuracy: 0.5512
Epoch 80/300
127/127 [==============================] - 0s 165us/step - loss: 1.1234 - accuracy: 0.5512
Epoch 81/300
127/127 [==============================] - 0s 173us/step - loss: 1.1226 - accuracy: 0.5512
Epoch 82/300
127/127 [==============================] - 0s 165us/step - loss: 1.1189 - accuracy: 0.5512
Epoch 83/300
127/127 [==============================] - 0s 173us/step - loss: 1.1167 - accuracy: 0.5591
Epoch 84/300
127/127 [==============================] - 0s 196us/step - loss: 1.1142 - accuracy: 0.5512
Epoch 85/300
127/127 [==============================] - 0s 165us/step - loss: 1.1115 - accuracy: 0.5512
Epoch 86/300
127/127 [==============================] - 0s 165us/step - loss:

Epoch 155/300
127/127 [==============================] - 0s 173us/step - loss: 0.7780 - accuracy: 0.7008
Epoch 156/300
127/127 [==============================] - 0s 188us/step - loss: 0.7728 - accuracy: 0.7087
Epoch 157/300
127/127 [==============================] - 0s 157us/step - loss: 0.7659 - accuracy: 0.7244
Epoch 158/300
127/127 [==============================] - 0s 173us/step - loss: 0.7613 - accuracy: 0.7402
Epoch 159/300
127/127 [==============================] - 0s 157us/step - loss: 0.7540 - accuracy: 0.7559
Epoch 160/300
127/127 [==============================] - 0s 149us/step - loss: 0.7484 - accuracy: 0.7480
Epoch 161/300
127/127 [==============================] - 0s 165us/step - loss: 0.7401 - accuracy: 0.7480
Epoch 162/300
127/127 [==============================] - 0s 149us/step - loss: 0.7347 - accuracy: 0.7559
Epoch 163/300
127/127 [==============================] - ETA: 0s - loss: 0.9994 - accuracy: 0.60 - 0s 149us/step - loss: 0.7262 - accuracy: 0.7480
Epoch 164/300

127/127 [==============================] - 0s 133us/step - loss: 0.4072 - accuracy: 0.8346
Epoch 233/300
127/127 [==============================] - 0s 133us/step - loss: 0.4062 - accuracy: 0.8346
Epoch 234/300
127/127 [==============================] - 0s 126us/step - loss: 0.4045 - accuracy: 0.8346
Epoch 235/300
127/127 [==============================] - 0s 126us/step - loss: 0.4043 - accuracy: 0.8346
Epoch 236/300
127/127 [==============================] - 0s 126us/step - loss: 0.4026 - accuracy: 0.8346
Epoch 237/300
127/127 [==============================] - 0s 126us/step - loss: 0.4014 - accuracy: 0.8346
Epoch 238/300
127/127 [==============================] - 0s 133us/step - loss: 0.4003 - accuracy: 0.8346
Epoch 239/300
127/127 [==============================] - 0s 126us/step - loss: 0.3934 - accuracy: 0.8346
Epoch 240/300
127/127 [==============================] - 0s 126us/step - loss: 0.3903 - accuracy: 0.8425
Epoch 241/300
127/127 [==============================] - 0s 118us/ste

In [24]:
y_pred = model.predict(x_test)

In [27]:
y_pred

array([[9.79748905e-01, 1.94689464e-02, 3.26404468e-08, 5.74291698e-05,
        1.66755381e-05, 1.31036518e-28, 7.08019361e-04],
       [5.85457349e-10, 8.00563302e-03, 5.21146178e-01, 1.23513578e-11,
        4.65955317e-01, 1.16048066e-03, 3.73243890e-03],
       [4.21045920e-10, 5.99225401e-04, 8.31671238e-01, 1.82942411e-10,
        1.34833112e-01, 3.10865846e-02, 1.80989923e-03],
       [2.38369324e-08, 1.27129117e-02, 5.28854430e-01, 1.52185164e-09,
        4.47697937e-01, 4.46501857e-04, 1.02882124e-02],
       [5.26210759e-03, 3.72957136e-03, 7.46592224e-01, 2.29449682e-02,
        5.34858666e-02, 1.58385027e-10, 1.67985231e-01],
       [4.10193868e-04, 4.07350381e-05, 9.62873876e-01, 2.58554332e-03,
        2.63401540e-03, 3.28394442e-17, 3.14556509e-02],
       [6.15967922e-02, 9.11377836e-03, 4.82220739e-01, 2.41755228e-02,
        3.76473404e-02, 1.50420611e-16, 3.85245860e-01],
       [1.42118381e-02, 1.10746769e-04, 2.49010205e-01, 6.67850077e-01,
        3.03945784e-03, 1

In [28]:
y_pred = model.predict_classes(x_test)

In [29]:
y_pred

array([0, 2, 2, 2, 2, 2, 2, 3, 0, 2, 2, 3, 2, 2, 4, 2, 2, 3, 2, 0, 4, 6,
       2, 3, 4, 0, 0, 4, 2, 5, 0, 2], dtype=int64)

In [30]:
y_test

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
 

In [31]:
y_p=model.predict_classes(sc.transform([[242,23.2,25.4,30.0,11.52,4.02]]))

In [32]:
y_p

array([1], dtype=int64)

In [38]:
y_p=model.predict_classes(sc.transform([[430,35.5,38,40.5,7.29,4.5765]]))

In [39]:
y_p

array([3], dtype=int64)

In [40]:
index=['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt']

In [41]:
class1=index[y_p[0]]

In [42]:
class1

'Parkki'