In [1]:
import pandas as pd
import numpy as np

In [3]:
dataset=pd.read_csv(r"C:\Users\PRAKASH KATIKANENI\Downloads\churn_modelling.csv")

In [4]:
type(dataset)

pandas.core.frame.DataFrame

In [5]:
dataset.isnull().any()

RowNumber          False
CustomerId         False
Surname            False
CreditScore        False
Geography          False
Gender             False
Age                False
Tenure             False
Balance            False
NumOfProducts      False
HasCrCard          False
IsActiveMember     False
EstimatedSalary    False
Exited             False
dtype: bool

In [7]:
dataset.head(10)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          225     Spain  Female   41   
2          3    15619304      Onio          629    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   
5          6    15574012       Chu          645     Spain    Male   44   
6          7    15592531  Bartlett          822    France    Male   50   
7          8    15656148    Obinna          376   Germany  Female   29   
8          9    15792365        He          501    France    Male   44   
9         10    15592389        H?          684    France    Male   27   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   
5       8  113755.78              2          1               0   
6       7       0.00              2          1               1   
7       4  115046.74              4          1               0   
8       4  142051.07              2          0               1   
9       2  134603.88              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0  
5        149756.71       1  
6         10062.80       0  
7        119346.88       1  
8         74940.50       0  
9         71725.73       0

In [9]:
p=dataset['Geography'].mode()

In [10]:
p

0    France
dtype: object

In [11]:
p[0]

'France'

In [12]:
dataset['Geography'].mode()[0]

'France'

In [14]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
dataset['Geography']=le.fit_transform(dataset['Geography'])

In [15]:
dataset['Gender']=le.fit_transform(dataset['Gender'])

In [16]:
dataset.head(10)

RowNumber  CustomerId   Surname  CreditScore  Geography  Gender  Age  \
0          1    15634602  Hargrave          619          0       0   42   
1          2    15647311      Hill          225          2       0   41   
2          3    15619304      Onio          629          0       0   42   
3          4    15701354      Boni          699          0       0   39   
4          5    15737888  Mitchell          850          2       0   43   
5          6    15574012       Chu          645          2       1   44   
6          7    15592531  Bartlett          822          0       1   50   
7          8    15656148    Obinna          376          1       0   29   
8          9    15792365        He          501          0       1   44   
9         10    15592389        H?          684          0       1   27   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   
5       8  113755.78              2          1               0   
6       7       0.00              2          1               1   
7       4  115046.74              4          1               0   
8       4  142051.07              2          0               1   
9       2  134603.88              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0  
5        149756.71       1  
6         10062.80       0  
7        119346.88       1  
8         74940.50       0  
9         71725.73       0

In [17]:
x=dataset.iloc[:,3:13].values

In [18]:
y=dataset.iloc[:,13].values

In [19]:
x

array([[6.1900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [2.2500000e+02, 2.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [6.2900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [7.0900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [7.7200000e+02, 1.0000000e+00, 1.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [7.9200000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [20]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [21]:
type(y)

numpy.ndarray

In [22]:
x.shape

(10000, 10)

In [23]:
from sklearn.preprocessing import OneHotEncoder
one=OneHotEncoder()
z=one.fit_transform(x[:,1:2]).toarray()

In [24]:
x=np.delete(x,1,axis=1)
x

array([[6.1900000e+02, 0.0000000e+00, 4.2000000e+01, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [2.2500000e+02, 0.0000000e+00, 4.1000000e+01, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [6.2900000e+02, 0.0000000e+00, 4.2000000e+01, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [7.0900000e+02, 0.0000000e+00, 3.6000000e+01, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [7.7200000e+02, 1.0000000e+00, 4.2000000e+01, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [7.9200000e+02, 0.0000000e+00, 2.8000000e+01, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [25]:
x=np.concatenate((z,x),axis=1)

In [26]:
z

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [27]:
 x.shape

(10000, 12)

In [28]:
y.shape

(10000,)

In [32]:
#split the data into train and test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [33]:
x_test.shape

(2000, 12)

In [34]:
y_test.shape

(2000,)

In [35]:
x_train.shape

(8000, 12)

In [36]:
y_train.shape

(8000,)

In [37]:
x_train[:,5:10]

array([[3.4000000e+01, 5.0000000e+00, 0.0000000e+00, 2.0000000e+00,
        1.0000000e+00],
       [4.2000000e+01, 1.0000000e+00, 7.5681520e+04, 1.0000000e+00,
        1.0000000e+00],
       [2.9000000e+01, 2.0000000e+00, 1.1236734e+05, 1.0000000e+00,
        1.0000000e+00],
       ...,
       [3.5000000e+01, 5.0000000e+00, 1.6127405e+05, 2.0000000e+00,
        1.0000000e+00],
       [3.8000000e+01, 9.0000000e+00, 0.0000000e+00, 2.0000000e+00,
        1.0000000e+00],
       [4.8000000e+01, 1.0000000e+00, 1.0807633e+05, 1.0000000e+00,
        1.0000000e+00]])

In [38]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [39]:
x_train

array([[-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [49]:
#1. Importing libraries
import keras
from keras.layers import Dense #Dense is the wich intializes the ip ,hidden layers
from keras.models import Sequential #Sequential is used to intialize the type of models

In [52]:
model = Sequential() #it will work in sequential process (ANN architecture is sequential) 

In [53]:
x_train.shape

(8000, 12)

In [64]:
# adding input layer
model.add(Dense(units=12,init ='random_uniform',activation='relu')) #units is all bout how many inputs u r trying to give.

C:\Users\PRAKASH KATIKANENI\anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=12, activation="relu", kernel_initializer="random_uniform")`
  


In [65]:
#adding an hidden layer 1
model.add(Dense(units=6,init = 'random_uniform' ,activation='relu'))

C:\Users\PRAKASH KATIKANENI\anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=6, activation="relu", kernel_initializer="random_uniform")`
  


In [66]:
model.add(Dense(units=1 ,init ='random_uniform',activation = 'sigmoid')) #as it is a classification probelm we are using sigmoid

C:\Users\PRAKASH KATIKANENI\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=1, activation="sigmoid", kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [67]:
model.compile(optimizer = 'adam',loss = 'binary_crossentropy',metrics =['accuracy'])

In [68]:
model.fit(x_train,y_train,batch_size=32,epochs=100) #epochs -How many times u want to train the data

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

Epoch 1/100
8000/8000 [==============================] - 2s 242us/step - loss: 0.6317 - accuracy: 0.7928
Epoch 2/100
8000/8000 [==============================] - 0s 48us/step - loss: 0.5087 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 0s 49us/step - loss: 0.5058 - accuracy: 0.7960
Epoch 4/100
8000/8000 [==============================] - 0s 55us/step - loss: 0.5057 - accuracy: 0.7960
Epoch 5/100
8000/8000 [==============================] - 0s 47us/step - loss: 0.5056 - accuracy: 0.7960
Epoch 6/100
8000/8000 [==============================] - 0s 46us/step - loss: 0.5054 - accuracy: 0.7960
Epoch 7/100
8000/8000 [==============================] - 0s 47us/step - loss: 0.5053 - accuracy: 0.7960
Epoch 8/100
8000/8000 [==============================] - 0s 55us/step - loss: 0.5048 - accuracy: 0.7960
Epoch 9/100
8000/8000 [==============================] - 0s 53us/step - 

8000/8000 [==============================] - 0s 51us/step - loss: 0.4120 - accuracy: 0.8179
Epoch 74/100
8000/8000 [==============================] - 0s 57us/step - loss: 0.4119 - accuracy: 0.8192
Epoch 75/100
8000/8000 [==============================] - 1s 66us/step - loss: 0.4116 - accuracy: 0.8188
Epoch 76/100
8000/8000 [==============================] - ETA: 0s - loss: 0.4122 - accuracy: 0.81 - 0s 55us/step - loss: 0.4116 - accuracy: 0.8195
Epoch 77/100
8000/8000 [==============================] - 0s 55us/step - loss: 0.4114 - accuracy: 0.8210
Epoch 78/100
8000/8000 [==============================] - 0s 56us/step - loss: 0.4109 - accuracy: 0.8201
Epoch 79/100
8000/8000 [==============================] - 0s 53us/step - loss: 0.4112 - accuracy: 0.8204
Epoch 80/100
8000/8000 [==============================] - 0s 53us/step - loss: 0.4106 - accuracy: 0.8215
Epoch 81/100
8000/8000 [==============================] - 0s 52us/step - loss: 0.4103 - accuracy: 0.8205
Epoch 82/100
8000/8000 [==

In [69]:
y_pred = model.predict(x_test)

In [71]:
y_pred

array([[0.16153866],
       [0.56840205],
       [0.09912947],
       ...,
       [0.09176379],
       [0.09207013],
       [0.09183326]], dtype=float32)

In [72]:
y_pred=(y_pred >0.5)

In [74]:
y_pred

array([[False],
       [ True],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [75]:
y_test

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [76]:
dataset.head(1)

RowNumber  CustomerId   Surname  CreditScore  Geography  Gender  Age  \
0          1    15634602  Hargrave          619          0       0   42   

   Tenure  Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  \
0       2      0.0              1          1               1        101348.88   

   Exited  
0       1

In [79]:
y_p = model.predict(sc.transfrom(np.array([[1,0,0,619,0,42,8,12345,1,1,1,123456]])))

AttributeError: 'StandardScaler' object has no attribute 'transfrom'