In [3]:
import numpy as np
import pandas as pd

In [4]:
dataset=pd.read_csv(r"C:\Users\PRAKASH KATIKANENI\Downloads\50_startups.csv")

In [5]:
dataset.head(2)

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.2       136897.80        471784.10    New York  192261.83
1   162597.7       151377.59        443898.53  California  191792.06

In [6]:
dataset.isnull().any()

R&D Spend          False
Administration     False
Marketing Spend    False
State              False
Profit             False
dtype: bool

In [7]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
dataset['State']=le.fit_transform(dataset['State'])

In [8]:
dataset.head()

R&D Spend  Administration  Marketing Spend  State     Profit
0  165349.20       136897.80        471784.10      2  192261.83
1  162597.70       151377.59        443898.53      0  191792.06
2  153441.51       101145.55        407934.54      1  191050.39
3  144372.41       118671.85        383199.62      2  182901.99
4  142107.34        91391.77        366168.42      1  166187.94

In [9]:
x=dataset.iloc[:,0:4].values
y=dataset.iloc[:,4:5].values

In [10]:
from sklearn.preprocessing import OneHotEncoder
one=OneHotEncoder()
z=one.fit_transform(x[:,3:4]).toarray()
x=np.delete(x,3,axis=1)
x=np.concatenate((z,x),axis=1)

In [11]:
from sklearn.model_selection import train_test_split
x_train ,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [12]:
x_train.shape

(40, 6)

In [13]:
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.
C:\Users\PRAKASH KATIKANENI\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\PRAKASH KATIKANENI\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\PRAKASH KATIKANENI\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\PRAKASH KATIKANENI\anaconda3\lib

In [14]:
regressor=Sequential()

In [15]:
x_train.shape

(40, 6)

In [16]:
regressor.add(Dense(units = 6,init = 'random_uniform',activation = 'relu'))

C:\Users\PRAKASH KATIKANENI\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=6, activation="relu", kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [20]:
regressor.add(Dense(units = 12,init = 'random_uniform',activation = 'relu')) 
#first hidden

C:\Users\PRAKASH KATIKANENI\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=12, activation="relu", kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [21]:
regressor.add(Dense(units = 8,init = 'random_uniform',activation = 'relu'))
#second hidden

C:\Users\PRAKASH KATIKANENI\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=8, activation="relu", kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [23]:
regressor.add(Dense(units = 9,init = 'random_uniform',activation = 'relu'))
#third hidden

C:\Users\PRAKASH KATIKANENI\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=9, activation="relu", kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [24]:
regressor.add(Dense(units = 1,init = 'random_uniform'))

C:\Users\PRAKASH KATIKANENI\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=1, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [25]:
regressor.compile (optimizer = 'adam',loss = 'mse',metrics = ['mse'])

In [26]:
regressor.fit(x_train,y_train , batch_size = 10,epochs = 300)


Epoch 1/300
40/40 [==============================] - 1s 31ms/step - loss: 13615995648.0000 - mse: 13615995904.0000
Epoch 2/300
40/40 [==============================] - 0s 485us/step - loss: 13615994880.0000 - mse: 13615994880.0000
Epoch 3/300
40/40 [==============================] - 0s 380us/step - loss: 13615992064.0000 - mse: 13615991808.0000
Epoch 4/300
40/40 [==============================] - 0s 258us/step - loss: 13615989248.0000 - mse: 13615988736.0000
Epoch 5/300
40/40 [==============================] - 0s 303us/step - loss: 13615981312.0000 - mse: 13615981568.0000
Epoch 6/300
40/40 [==============================] - 0s 344us/step - loss: 13615962112.0000 - mse: 13615962112.0000
Epoch 7/300
40/40 [==============================] - 0s 255us/step - loss: 13615917568.0000 - mse: 13615917056.0000
Epoch 8/300
40/40 [==============================] - 0s 310us/step - loss: 13615827200.0000 - mse: 13615826944.0000
Epoch 9/300
40/40 [==============================] - 0s 332us/step - los

40/40 [==============================] - 0s 292us/step - loss: 215158124.0000 - mse: 215158112.0000
Epoch 143/300
40/40 [==============================] - 0s 242us/step - loss: 216115922.0000 - mse: 216115920.0000
Epoch 144/300
40/40 [==============================] - 0s 262us/step - loss: 213304244.0000 - mse: 213304240.0000
Epoch 145/300
40/40 [==============================] - 0s 208us/step - loss: 213859492.0000 - mse: 213859488.0000
Epoch 146/300
40/40 [==============================] - 0s 226us/step - loss: 212576480.0000 - mse: 212576480.0000
Epoch 147/300
40/40 [==============================] - 0s 256us/step - loss: 211392456.0000 - mse: 211392464.0000
Epoch 148/300
40/40 [==============================] - 0s 315us/step - loss: 209970820.0000 - mse: 209970832.0000
Epoch 149/300
40/40 [==============================] - 0s 307us/step - loss: 209261000.0000 - mse: 209261008.0000
Epoch 150/300
40/40 [==============================] - 0s 307us/step - loss: 207629162.5000 - mse: 207

40/40 [==============================] - 0s 220us/step - loss: 167981542.0000 - mse: 167981536.0000
Epoch 214/300
40/40 [==============================] - 0s 260us/step - loss: 168212706.0000 - mse: 168212704.0000
Epoch 215/300
40/40 [==============================] - 0s 220us/step - loss: 167456960.0000 - mse: 167456944.0000
Epoch 216/300
40/40 [==============================] - 0s 274us/step - loss: 167354818.0000 - mse: 167354832.0000
Epoch 217/300
40/40 [==============================] - ETA: 0s - loss: 124496744.0000 - mse: 124496744.000 - 0s 224us/step - loss: 166597186.0000 - mse: 166597200.0000
Epoch 218/300
40/40 [==============================] - 0s 599us/step - loss: 166410070.0000 - mse: 166410064.0000
Epoch 219/300
40/40 [==============================] - 0s 319us/step - loss: 166362786.0000 - mse: 166362784.0000
Epoch 220/300
40/40 [==============================] - 0s 374us/step - loss: 167367390.0000 - mse: 167367392.0000
Epoch 221/300
40/40 [===========================

40/40 [==============================] - 0s 429us/step - loss: 154073980.0000 - mse: 154073984.0000
Epoch 285/300
40/40 [==============================] - 0s 576us/step - loss: 153271103.0000 - mse: 153271104.0000
Epoch 286/300
40/40 [==============================] - 0s 363us/step - loss: 152687374.0000 - mse: 152687376.0000
Epoch 287/300
40/40 [==============================] - 0s 238us/step - loss: 152342146.0000 - mse: 152342128.0000
Epoch 288/300
40/40 [==============================] - 0s 206us/step - loss: 152332952.0000 - mse: 152332960.0000
Epoch 289/300
40/40 [==============================] - 0s 219us/step - loss: 151948576.0000 - mse: 151948576.0000
Epoch 290/300
40/40 [==============================] - 0s 259us/step - loss: 153219832.0000 - mse: 153219840.0000
Epoch 291/300
40/40 [==============================] - 0s 303us/step - loss: 152421930.0000 - mse: 152421936.0000
Epoch 292/300
40/40 [==============================] - 0s 240us/step - loss: 152729412.0000 - mse: 152

In [27]:
y_pred = regressor.predict(x_test)

In [28]:
y_pred

array([[119074.33 ],
       [119341.73 ],
       [125292.914],
       [ 62477.54 ],
       [170040.86 ],
       [122431.945],
       [ 52387.977],
       [102525.34 ],
       [117701.68 ],
       [155692.42 ]], dtype=float32)

In [29]:
y_test

array([[103282.38],
       [144259.4 ],
       [146121.95],
       [ 77798.83],
       [191050.39],
       [105008.31],
       [ 81229.06],
       [ 97483.56],
       [110352.25],
       [166187.94]])

In [30]:
from sklearn.metrics import r2_score
accuracy =r2_score(y_test,y_pred)

In [31]:
accuracy

0.7415537074024752

In [32]:
regressor.save('regressor.h5')

In [33]:
x_train.shape

(40, 6)

In [34]:
regressor.predict(np.array([[0,1,0,50000,60000,70000]]))

array([[60066.46]], dtype=float32)