In [1]:
# importing libaries
import pandas as pd
import numpy as np

In [2]:
dataset=pd.read_csv(r"C:\Users\PRAKASH KATIKANENI\Downloads\bank.csv")

In [3]:
dataset

age          job  marital  education default  balance housing loan  \
0       59       admin.  married  secondary      no     2343     yes   no   
1       56       admin.  married  secondary      no       45      no   no   
2       41   technician  married  secondary      no     1270     yes   no   
3       55     services  married  secondary      no     2476     yes   no   
4       54       admin.  married   tertiary      no      184      no   no   
...    ...          ...      ...        ...     ...      ...     ...  ...   
11157   33  blue-collar   single    primary      no        1     yes   no   
11158   39     services  married  secondary      no      733      no   no   
11159   32   technician   single  secondary      no       29      no   no   
11160   43   technician  married  secondary      no        0      no  yes   
11161   34   technician  married  secondary      no        0      no   no   

        contact  day month  duration  campaign  pdays  previous poutcome  \
0       unknown    5   may      1042         1     -1         0  unknown   
1       unknown    5   may      1467         1     -1         0  unknown   
2       unknown    5   may      1389         1     -1         0  unknown   
3       unknown    5   may       579         1     -1         0  unknown   
4       unknown    5   may       673         2     -1         0  unknown   
...         ...  ...   ...       ...       ...    ...       ...      ...   
11157  cellular   20   apr       257         1     -1         0  unknown   
11158   unknown   16   jun        83         4     -1         0  unknown   
11159  cellular   19   aug       156         2     -1         0  unknown   
11160  cellular    8   may         9         2    172         5  failure   
11161  cellular    9   jul       628         1     -1         0  unknown   

      deposit  
0         yes  
1         yes  
2         yes  
3         yes  
4         yes  
...       ...  
11157      no  
11158      no  
11159      no  
11160      no  
11161      no  

[11162 rows x 17 columns]

In [4]:
dataset.isnull().any()

age          False
job          False
marital      False
education    False
default      False
balance      False
housing      False
loan         False
contact      False
day          False
month        False
duration     False
campaign     False
pdays        False
previous     False
poutcome     False
deposit      False
dtype: bool

In [5]:
dataset["marital"].unique()

array(['married', 'single', 'divorced'], dtype=object)

In [6]:
dataset["job"].unique()

array(['admin.', 'technician', 'services', 'management', 'retired',
       'blue-collar', 'unemployed', 'entrepreneur', 'housemaid',
       'unknown', 'self-employed', 'student'], dtype=object)

In [7]:
dataset["education"].unique()

array(['secondary', 'tertiary', 'primary', 'unknown'], dtype=object)

In [8]:
dataset["contact"].unique()

array(['unknown', 'cellular', 'telephone'], dtype=object)

In [9]:
dataset["month"].unique()

array(['may', 'jun', 'jul', 'aug', 'oct', 'nov', 'dec', 'jan', 'feb',
       'mar', 'apr', 'sep'], dtype=object)

In [10]:
dataset["poutcome"].unique()

array(['unknown', 'other', 'failure', 'success'], dtype=object)

In [11]:
dataset["loan"].unique()

array(['no', 'yes'], dtype=object)

In [12]:
dataset["housing"].unique()

array(['yes', 'no'], dtype=object)

In [13]:
dataset.head(1)

age     job  marital  education default  balance housing loan  contact  \
0   59  admin.  married  secondary      no     2343     yes   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1     -1         0  unknown     yes

In [14]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
dataset['job']=le.fit_transform(dataset['job'])
dataset['marital']=le.fit_transform(dataset['marital'])
dataset['eduaction']=le.fit_transform(dataset['education'])
dataset['default']=le.fit_transform(dataset['default'])
dataset['housing']=le.fit_transform(dataset['housing'])
dataset['loan']=le.fit_transform(dataset['loan'])
dataset['contact']=le.fit_transform(dataset['contact'])
dataset['month']=le.fit_transform(dataset['month'])
dataset['poutcome']=le.fit_transform(dataset['poutcome'])
dataset['deposit']=le.fit_transform(dataset['deposit'])

In [15]:
dataset.head(10)

age  job  marital  education  default  balance  housing  loan  contact  \
0   59    0        1  secondary        0     2343        1     0        2   
1   56    0        1  secondary        0       45        0     0        2   
2   41    9        1  secondary        0     1270        1     0        2   
3   55    7        1  secondary        0     2476        1     0        2   
4   54    0        1   tertiary        0      184        0     0        2   
5   42    4        2   tertiary        0        0        1     1        2   
6   56    4        1   tertiary        0      830        1     1        2   
7   60    5        0  secondary        0      545        1     0        2   
8   37    9        1  secondary        0        1        1     0        2   
9   28    7        2  secondary        0     5090        1     0        2   

   day  month  duration  campaign  pdays  previous  poutcome  deposit  \
0    5      8      1042         1     -1         0         3        1   
1    5      8      1467         1     -1         0         3        1   
2    5      8      1389         1     -1         0         3        1   
3    5      8       579         1     -1         0         3        1   
4    5      8       673         2     -1         0         3        1   
5    5      8       562         2     -1         0         3        1   
6    6      8      1201         1     -1         0         3        1   
7    6      8      1030         1     -1         0         3        1   
8    6      8       608         1     -1         0         3        1   
9    6      8      1297         3     -1         0         3        1   

   eduaction  
0          1  
1          1  
2          1  
3          1  
4          2  
5          2  
6          2  
7          1  
8          1  
9          1

In [16]:
x=dataset.iloc[:,0:16].values

In [17]:
x

array([[59, 0, 1, ..., -1, 0, 3],
       [56, 0, 1, ..., -1, 0, 3],
       [41, 9, 1, ..., -1, 0, 3],
       ...,
       [32, 9, 2, ..., -1, 0, 3],
       [43, 9, 1, ..., 172, 5, 0],
       [34, 9, 1, ..., -1, 0, 3]], dtype=object)

In [18]:
y=dataset.iloc[:,16:17].values

In [19]:
y

array([[1],
       [1],
       [1],
       ...,
       [0],
       [0],
       [0]])

In [20]:
x.shape

(11162, 16)

In [21]:
y.shape

(11162, 1)

In [22]:
from sklearn.preprocessing import OneHotEncoder
one=OneHotEncoder()
a=one.fit_transform(x[:,1:2]).toarray()
b=one.fit_transform(x[:,2:3]).toarray()
c=one.fit_transform(x[:,3:4]).toarray()
d=one.fit_transform(x[:,8:9]).toarray()
e=one.fit_transform(x[:,10:11]).toarray()
g=one.fit_transform(x[:,15:16]).toarray()
x=np.delete(x,[1,2,3,8,10,15],axis=1)

In [23]:
x.shape

(11162, 10)

In [24]:
x=np.concatenate((g,e,d,c,b,a,x),axis=1)

In [25]:
x.shape

(11162, 48)

In [26]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [27]:
x_test.shape

(2233, 48)

In [28]:
y_test.shape

(2233, 1)

In [30]:
x_train.shape

(8929, 48)

In [31]:
y_train.shape

(8929, 1)

In [34]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [36]:
x_train

array([[-0.35031555, -0.22657536, -0.32939951, ..., -0.56394809,
        -0.48428507, -0.35888264],
       [-0.35031555, -0.22657536, -0.32939951, ..., -0.56394809,
        -0.48428507, -0.35888264],
       [-0.35031555, -0.22657536, -0.32939951, ...,  0.92827075,
        -0.48428507, -0.35888264],
       ...,
       [-0.35031555, -0.22657536, -0.32939951, ...,  2.04743488,
        -0.48428507, -0.35888264],
       [-0.35031555, -0.22657536, -0.32939951, ..., -0.56394809,
        -0.48428507, -0.35888264],
       [-0.35031555, -0.22657536, -0.32939951, ..., -0.56394809,
        -0.48428507, -0.35888264]])

In [37]:
dataset.describe()

age           job       marital       default       balance  \
count  11162.000000  11162.000000  11162.000000  11162.000000  11162.000000   
mean      41.231948      4.487905      1.199337      0.015051   1528.538524   
std       11.913369      3.225132      0.625552      0.121761   3225.413326   
min       18.000000      0.000000      0.000000      0.000000  -6847.000000   
25%       32.000000      1.000000      1.000000      0.000000    122.000000   
50%       39.000000      4.000000      1.000000      0.000000    550.000000   
75%       49.000000      7.000000      2.000000      0.000000   1708.000000   
max       95.000000     11.000000      2.000000      1.000000  81204.000000   

            housing          loan       contact           day         month  \
count  11162.000000  11162.000000  11162.000000  11162.000000  11162.000000   
mean       0.473123      0.130801      0.489697     15.658036      5.445709   
std        0.499299      0.337198      0.818724      8.420740      3.191939   
min        0.000000      0.000000      0.000000      1.000000      0.000000   
25%        0.000000      0.000000      0.000000      8.000000      3.000000   
50%        0.000000      0.000000      0.000000     15.000000      6.000000   
75%        1.000000      0.000000      1.000000     22.000000      8.000000   
max        1.000000      1.000000      2.000000     31.000000     11.000000   

           duration      campaign         pdays      previous      poutcome  \
count  11162.000000  11162.000000  11162.000000  11162.000000  11162.000000   
mean     371.993818      2.508421     51.330407      0.832557      2.477782   
std      347.128386      2.722077    108.758282      2.292007      1.002952   
min        2.000000      1.000000     -1.000000      0.000000      0.000000   
25%      138.000000      1.000000     -1.000000      0.000000      2.000000   
50%      255.000000      2.000000     -1.000000      0.000000      3.000000   
75%      496.000000      3.000000     20.750000      1.000000      3.000000   
max     3881.000000     63.000000    854.000000     58.000000      3.000000   

            deposit     eduaction  
count  11162.000000  11162.000000  
mean       0.473840      1.285164  
std        0.499338      0.749478  
min        0.000000      0.000000  
25%        0.000000      1.000000  
50%        0.000000      1.000000  
75%        1.000000      2.000000  
max        1.000000      3.000000