In [2]:
import numpy 
import numpy as np
from numpy import*

In [3]:
list1=[1,2,3]

In [4]:
list1

[1, 2, 3]

In [6]:
arr=numpy.array(list1) #import numpy

In [7]:
arr

array([1, 2, 3])

In [8]:
arr=np.array(list1) #import numpy as np

In [9]:
arr

array([1, 2, 3])

In [12]:
arr=array(list1) #from numpy import* (no need of mentioning class name)

In [13]:
arr

array([1, 2, 3])

In [14]:
type(arr)

numpy.ndarray

In [17]:
arr.shape  # row matrix with 3 elements  in it

(3,)

In [19]:
arr.ndim  #ndim ->ndimensional

1

In [20]:
arr2=np.array([1,2,3,4,5,6])

In [21]:
arr2

array([1, 2, 3, 4, 5, 6])

In [23]:
arr2[2:5]

array([3, 4, 5])

In [25]:
arr2[4]=90

In [26]:
arr2

array([ 1,  2,  3,  4, 90,  6])

In [32]:
list1=[[1,2,3],[4,5,6],[7,8,9]] #creation of multi dimensional array

In [28]:
listarr=np.array(list1)

In [29]:
listarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
listarr.shape

(3, 3)

In [31]:
listarr.ndim

2

In [38]:
list2=[[1,2,3,4,5],[5,6,7,8,9],[0,9,8,7,1],[5,4,3,2,0]]

In [39]:
listarr2=array(list2)

In [40]:
listarr2

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9],
       [0, 9, 8, 7, 1],
       [5, 4, 3, 2, 0]])

In [41]:
listarr2.ndim

2

In [42]:
listarr2.shape

(4, 5)

In [43]:
listarr2[2]

array([0, 9, 8, 7, 1])

In [45]:
#listarr=[rows,coloums] way to access rows and columns
listarr2[:,3]

array([4, 8, 7, 2])

In [46]:
listarr2[2:4,2:5]

array([[8, 7, 1],
       [3, 2, 0]])

In [48]:
listarr2.diagonal()

array([1, 6, 8, 2])

In [49]:
listarr2[0,0]

1

In [50]:
listarr2[[0,1,3],[0,3,4]]

array([1, 8, 0])

In [51]:
dir(listarr2)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [54]:
#zeroarr=np.zeros((rows,colomns)) (rows,columns) in tuples
zeroarr=np.zeros((2,3))

In [55]:
zeroarr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [56]:
one=np.ones((2))

In [57]:
one

array([1., 1.])

In [59]:
type(one)

numpy.ndarray

In [62]:
one=np.ones((5,5))

In [63]:
one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [66]:
np.eye(4,5)  #eye -identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [67]:
arange=np.arange(20,30)

In [68]:
arange

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [69]:
arange.reshape(2,5)

array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [70]:
arange.reshape(5,2)

array([[20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

In [75]:
ar=np.arange(16)

In [76]:
ar


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [77]:
ar.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [78]:
ar.reshape(2,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [79]:
ar.reshape(8,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [85]:
np.random.rand(2)  #generates random number between 0-1

array([0.4796984 , 0.23024254])

In [86]:
np.random.rand(4,5)

array([[0.56149853, 0.12251453, 0.75318121, 0.22356906, 0.91995315],
       [0.4978264 , 0.64792021, 0.11659451, 0.44930019, 0.81971299],
       [0.93874454, 0.59057551, 0.65035979, 0.46442218, 0.65916918],
       [0.28717947, 0.53262311, 0.16258561, 0.33737672, 0.68457946]])

In [87]:
np.random.randint(1,25,10) #10 here represnts no of elemnets to be generated

array([21,  6, 18,  5, 20,  8,  8,  1, 22,  1])

In [84]:
np.random.randint(1,25)

3

In [88]:
np.random.randint(1,25,10).reshape(2,5)

array([[11, 23, 14, 21,  5],
       [21, 22, 10,  6,  4]])

In [89]:
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [91]:
np.linspace(1,10,20) # 1,10 is range in which elements are neede dto be display 20 no.of elements needed to display

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [94]:
p=np.random.randint(1,100,25).reshape(5,5)

In [95]:
p

array([[ 5, 72, 93, 17, 82],
       [69, 69, 75, 51,  8],
       [53, 74, 21,  3, 32],
       [10, 79, 48, 22,  1],
       [35, 34, 86, 48, 83]])

In [96]:
q=p.ravel()

In [97]:
q

array([ 5, 72, 93, 17, 82, 69, 69, 75, 51,  8, 53, 74, 21,  3, 32, 10, 79,
       48, 22,  1, 35, 34, 86, 48, 83])

In [99]:
s=p.flatten()

In [100]:
s

array([ 5, 72, 93, 17, 82, 69, 69, 75, 51,  8, 53, 74, 21,  3, 32, 10, 79,
       48, 22,  1, 35, 34, 86, 48, 83])

In [101]:
q[1]=100

In [102]:
q

array([  5, 100,  93,  17,  82,  69,  69,  75,  51,   8,  53,  74,  21,
         3,  32,  10,  79,  48,  22,   1,  35,  34,  86,  48,  83])

In [103]:
p

array([[  5, 100,  93,  17,  82],
       [ 69,  69,  75,  51,   8],
       [ 53,  74,  21,   3,  32],
       [ 10,  79,  48,  22,   1],
       [ 35,  34,  86,  48,  83]])

In [104]:
s[3]=12

In [105]:
s

array([ 5, 72, 93, 12, 82, 69, 69, 75, 51,  8, 53, 74, 21,  3, 32, 10, 79,
       48, 22,  1, 35, 34, 86, 48, 83])

In [106]:
p

array([[  5, 100,  93,  17,  82],
       [ 69,  69,  75,  51,   8],
       [ 53,  74,  21,   3,  32],
       [ 10,  79,  48,  22,   1],
       [ 35,  34,  86,  48,  83]])

In [107]:
a=np.arange(9).reshape(3,3)

In [108]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [110]:
b=np.random.randint(0,9,9).reshape(3,3)

In [111]:
b

array([[8, 2, 2],
       [0, 5, 0],
       [0, 8, 7]])

In [114]:
c=np.concatenate((a,b))

In [115]:
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [8, 2, 2],
       [0, 5, 0],
       [0, 8, 7]])

In [118]:
d=np.concatenate((a,b),axis=1)   #concatenate row wise then axis=1 otherwise default row =0(eow wise concatentaion)

In [119]:
d

array([[0, 1, 2, 8, 2, 2],
       [3, 4, 5, 0, 5, 0],
       [6, 7, 8, 0, 8, 7]])

In [121]:
e=d.transpose()

In [122]:
e

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8],
       [8, 0, 0],
       [2, 5, 8],
       [2, 0, 7]])

In [123]:
s='hiiiii'
p='helooo'
f=s+p

In [124]:
f

'hiiiiihelooo'